import React, { createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { Activity, Bell, Check, Clock3, HeartPulse, History, LayoutDashboard, Mail, MapPin, Menu, Pill, Plus, QrCode, ScanLine, Settings, ShieldCheck, Trash2, Users, X } from 'lucide-react';
import './styles.css';

const seedMeds = [{id:1,name:'Metformin',dosage:'500 mg',frequency:'Twice daily',next:'8:00 PM',status:'Upcoming'},{id:2,name:'Amlodipine',dosage:'5 mg',frequency:'Once daily',next:'Tomorrow 8:00 AM',status:'Scheduled'},{id:3,name:'Vitamin D',dosage:'1 tablet',frequency:'Once weekly',next:'Sunday',status:'Scheduled'}];
const seedSchedule = [{id:1,name:'Metformin',dosage:'500 mg',time:'8:00 AM',status:'Taken'},{id:2,name:'Amlodipine',dosage:'5 mg',time:'1:00 PM',status:'Taken'},{id:3,name:'Metformin',dosage:'500 mg',time:'8:00 PM',status:'Upcoming'},{id:4,name:'Vitamin D',dosage:'1 tablet',time:'9:00 PM',status:'Upcoming'}];
const Store = createContext();
const useStore = () => useContext(Store);
function Provider({children}) {
  const [meds,setMeds] = useState(()=>JSON.parse(localStorage.getItem('caredose-meds')) || seedMeds);
  const [schedule,setSchedule] = useState(()=>JSON.parse(localStorage.getItem('caredose-schedule')) || seedSchedule);
  const [history,setHistory] = useState(()=>JSON.parse(localStorage.getItem('caredose-history')) || [{id:8,date:'Today',medicine:'Amlodipine',dosage:'5 mg',time:'1:00 PM',status:'Taken'},{id:7,date:'Yesterday',medicine:'Metformin',dosage:'500 mg',time:'8:00 PM',status:'Missed'}]);
  useEffect(()=>localStorage.setItem('caredose-meds',JSON.stringify(meds)),[meds]);
  useEffect(()=>localStorage.setItem('caredose-schedule',JSON.stringify(schedule)),[schedule]);
  useEffect(()=>localStorage.setItem('caredose-history',JSON.stringify(history)),[history]);
  const take = id => { const dose=schedule.find(x=>x.id===id); if(!dose || dose.status==='Taken') return; setSchedule(s=>s.map(x=>x.id===id?{...x,status:'Taken'}:x)); setHistory(h=>[{id:Date.now(),date:'Today',medicine:dose.name,dosage:dose.dosage,time:dose.time,status:'Taken'},...h]); };
  const add = m => setMeds(s=>[...s,{...m,id:Date.now(),status:'Scheduled'}]);
  return <Store.Provider value={{meds,setMeds,schedule,history,take,add}}>{children}</Store.Provider>;
}
const Logo=()=> <Link className="logo" to="/"><span><HeartPulse/></span>Care<b>Dose</b></Link>;
const Badge=({children})=><span className={'badge '+children.toLowerCase()}>{children==='Taken'&&<Check size={14}/>} {children}</span>;
function PublicNav(){return <header className="public-nav"><Logo/><nav><Link to="/">Home</Link><Link to="/about">How It Works</Link><Link to="/about">About</Link><Link to="/contact">Contact</Link><Link to="/login">Login</Link><Link className="button small" to="/register">Get Started</Link></nav></header>}
function Footer(){return <footer><Logo/><p>Right Medicine. Right Time. Peace of Mind.</p><div><Link to="/">Home</Link><Link to="/about">About</Link><Link to="/contact">Contact</Link></div><small>Copyright 2026 CareDose. All rights reserved.</small></footer>}
function Landing(){const nav=useNavigate();return <><PublicNav/><main><section className="hero"><div><p className="eyebrow"><ShieldCheck size={16}/> Trusted medication support</p><h1>Never Miss an Important <em>Dose</em> Again.</h1><p>CareDose makes medication management simple for seniors, chronic patients, and their caregivers.</p><button className="button" onClick={()=>nav('/register')}>Get Started</button> <button className="button ghost" onClick={()=>nav('/dashboard')}>View Demo</button><p className="helper">Simple medication management for patients and families.</p></div><div className="phone"><small>Good evening, Ramesh</small><h3>Your medicines</h3><div className="progress">2 of 4 doses completed <b>50%</b></div><article><span className="pill">M</span><div><b>Metformin</b><small>500 mg · 8:00 PM</small></div><Clock3/></article><button className="button full">Mark as taken</button></div></section><Section title="Everything You Need to Manage Medicines Better" items={[[Bell,'Smart Reminders','Get timely reminders for every medicine and dosage.'],[QrCode,'QR Medicine Identification','Scan a QR code to quickly identify your medicine.'],[Users,'Caregiver Alerts','Keep family members informed when a dose is missed.'],[History,'Medication History','Track completed and missed doses in one place.']]}/><section className="tinted steps"><h2>How CareDose Works</h2>{[['01','Add Medicine'],['02','Scan QR'],['03','Get Reminders'],['04','Stay Connected']].map(x=><article key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>Simple, clear support for each part of your medication routine.</p></div></article>)}</section><section className="cta"><h2>Take Control of Your Medication Routine</h2><p>CareDose helps you stay organized, confident, and connected.</p><button className="button light" onClick={()=>nav('/dashboard')}>View Demo</button></section></main><Footer/></>}
function Section({title,items}){return <section className="section"><h2>{title}</h2><div className="cards">{items.map(([I,t,d])=><article key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div></section>}
function Auth({register=false}){const nav=useNavigate();const [type,setType]=useState('Patient');return <div className="auth"><div><Logo/><h1>{register?'Create your account':'Welcome back'}</h1><p>Medication support that feels simple and calm.</p><form onSubmit={e=>{e.preventDefault();nav(type==='Caregiver'?'/caregiver':'/dashboard')}}>{register&&<><label>Full Name<input required placeholder="Your full name"/></label><label>User Type<select onChange={e=>setType(e.target.value)}><option>Patient</option><option>Caregiver</option></select></label></>}<label>Email<input required type="email" placeholder="you@example.com"/></label><label>Password<input required type="password" placeholder="At least 8 characters"/></label>{register&&<label>Confirm Password<input required type="password" placeholder="Repeat password"/></label>}<button className="button full">{register?'Create Account':'Login'}</button></form><p>{register?'Already have an account?':'New to CareDose?'} <Link to={register?'/login':'/register'}>{register?'Login':'Create one'}</Link></p></div></div>}
const links=[[LayoutDashboard,'Dashboard','/dashboard'],[Pill,'My Medicines','/medicines'],[Plus,'Add Medicine','/medicines/add'],[ScanLine,'QR Scanner','/scanner'],[Bell,'Reminders','/reminders'],[History,'Medication History','/history'],[Users,'Caregiver','/caregiver'],[Settings,'Settings','/dashboard']];
function Shell({title,subtitle,children}){const [open,setOpen]=useState(false);return <div className="app"><aside className={open?'open':''}><Logo/><button className="close" onClick={()=>setOpen(false)}><X/></button>{links.map(([I,t,to])=><NavLink key={t} to={to} onClick={()=>setOpen(false)}><I size={19}/>{t}</NavLink>)}</aside><main><header className="app-header"><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div><p className="eyebrow">CareDose overview</p><h1>{title}</h1><p>{subtitle}</p></div><span className="avatar">RK</span></header>{children}</main></div>}
function Dashboard(){const {schedule,take}=useStore();const next=schedule.find(x=>x.status==='Upcoming');return <Shell title="Good morning, Ramesh!" subtitle="Here is your medication plan for today."><div className="stats">{[['Today’s Medicines',4,Pill],['Taken',schedule.filter(x=>x.status==='Taken').length,Check],['Remaining',schedule.filter(x=>x.status==='Upcoming').length,Clock3],['Missed',0,Activity]].map(([t,n,I])=><article key={t}><I/><p>{t}</p><b>{n}</b></article>)}</div><div className="grid"><section className="panel"><p className="eyebrow">Next medicine</p><h2>{next?.name}</h2><p>{next?.dosage} · {next?.time}</p><Badge>Upcoming</Badge><button className="button full" onClick={()=>take(next?.id)}>Mark as Taken</button></section><section className="panel center"><p className="eyebrow">This week</p><strong className="adherence">92%</strong><p>Medication adherence</p></section></div><section className="panel"><h2>Today’s Schedule</h2>{schedule.map(x=><div className="row" key={x.id}><b>{x.time}</b><span className="pill">{x.name[0]}</span><div><b>{x.name}</b><small>{x.dosage}</small></div><Badge>{x.status}</Badge>{x.status==='Upcoming'&&<button className="text" onClick={()=>take(x.id)}>Take now</button>}</div>)}</section></Shell>}
function Medicines(){const {meds,setMeds}=useStore();return <Shell title="My Medicines" subtitle="Keep your complete medicine list in one clear place."><Link className="button add" to="/medicines/add"><Plus/>Add Medicine</Link><div className="medicine-grid">{meds.map(m=><article className="medicine" key={m.id}><button className="delete" onClick={()=>setMeds(s=>s.filter(x=>x.id!==m.id))}><Trash2/></button><span className="pill">{m.name[0]}</span><h2>{m.name}</h2><p>{m.dosage}</p><hr/><p>{m.frequency}</p><p>Next: {m.next}</p><Badge>{m.status}</Badge></article>)}</div></Shell>}
function AddMedicine(){const {add}=useStore();const nav=useNavigate();return <Shell title="Add Medicine" subtitle="Add the details so CareDose can help you stay on schedule."><form className="form panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.target);add({name:f.get('name'),dosage:f.get('dosage'),frequency:f.get('frequency'),next:f.get('time')});nav('/medicines')}}><label>Medicine Name<input name="name" required/></label><label>Dosage<input name="dosage" required placeholder="e.g. 500 mg"/></label><label>Frequency<select name="frequency"><option>Once daily</option><option>Twice daily</option><option>Once weekly</option></select></label><label>Time<input name="time" type="time" required/></label><label className="wide">Instructions<textarea rows="3" placeholder="e.g. Take after meals"/></label><label className="wide"><input type="checkbox" defaultChecked/> Enable caregiver notification</label><button className="button">Save Medicine</button></form></Shell>}
function Scanner(){const {add}=useStore();const nav=useNavigate();const [found,setFound]=useState(false);return <Shell title="QR Scanner" subtitle="Quickly identify a medicine with its QR code."><section className="scanner panel"><p className="eyebrow">Demo scanner</p><div className={'scan '+(found?'found':'')}>{found?<Check size={70}/>:<QrCode size={90}/>}</div>{found?<><h2>Medicine Found: Metformin 500 mg</h2><p>Dosage: 500 mg · Schedule: Twice daily</p><button className="button" onClick={()=>{add({name:'Metformin',dosage:'500 mg',frequency:'Twice daily',next:'8:00 PM'});nav('/medicines')}}>Add to My Medicines</button></>:<><h2>Scan Medicine QR Code</h2><p>Place the medicine QR code inside the frame.</p><button className="button" onClick={()=>setTimeout(()=>setFound(true),900)}>Start Scanner</button></>}</section></Shell>}
function Reminders(){const {schedule,take}=useStore();return <Shell title="Reminders" subtitle="Your clear plan for today’s medicines."><section className="panel timeline">{schedule.map(x=><div className="row" key={x.id}><b>{x.time}</b><span className="pill">{x.name[0]}</span><div><h3>{x.name}</h3><small>{x.dosage}</small></div><Badge>{x.status}</Badge>{x.status==='Upcoming'&&<button className="text" onClick={()=>take(x.id)}>Mark taken</button>}</div>)}</section></Shell>}
function HistoryPage(){const {history}=useStore();const [filter,setFilter]=useState('All');const data=filter==='All'?history:history.filter(x=>x.status===filter);return <Shell title="Medication History" subtitle="Review your medication activity and daily consistency."><div className="stats three"><article><Activity/><p>Adherence</p><b>92%</b></article><article><Check/><p>Doses Taken</p><b>46</b></article><article><Bell/><p>Missed</p><b>4</b></article></div><section className="panel"><h2>Recent Activity</h2><div className="tabs">{['All','Taken','Missed'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>{data.map(x=><div className="row" key={x.id}><span>{x.date}</span><b>{x.medicine}</b><span>{x.dosage}</span><span>{x.time}</span><Badge>{x.status}</Badge></div>)}</section></Shell>}
function Caregiver(){return <Shell title="Caregiver Dashboard" subtitle="Stay connected with Ramesh Kumar’s medication routine."><section className="alert"><p className="eyebrow">Missed dose alert</p><h2>Ramesh missed Metformin at 1:00 PM.</h2><p>A gentle reminder may help keep the routine on track.</p><button className="button light">Send a Reminder</button></section><div className="stats">{[['Medication Adherence','92%',Activity],['Today’s Doses','4',Pill],['Completed','3',Check],['Missed','1',Bell]].map(([t,n,I])=><article key={t}><I/><p>{t}</p><b>{n}</b></article>)}</div></Shell>}
function About(){return <><PublicNav/><main><section className="info"><p className="eyebrow">About CareDose</p><h1>Medication support that feels <em>human.</em></h1><p>Managing multiple medicines can be difficult for seniors and chronic patients. CareDose combines reminders, QR identification, tracking, and caregiver alerts in one simple platform.</p></section><Section title="Designed for peace of mind" items={[[HeartPulse,'Our Mission','To make medication management simpler, safer, and more convenient.'],[QrCode,'Our Solution','Smart reminders and clear tracking in one place.'],[Users,'For Caregivers','Better visibility and more peace of mind.']]}/></main><Footer/></>}
function Contact(){const [sent,setSent]=useState(false);return <><PublicNav/><main className="contact"><section><p className="eyebrow">We are here to help</p><h1>Get in Touch</h1><p>Questions, ideas, or feedback? Our team would be glad to hear from you.</p><p><Mail/> support@caredose.com</p><p><MapPin/> Hyderabad, India</p></section><form className="panel" onSubmit={e=>{e.preventDefault();setSent(true)}}><h2>Send a message</h2>{sent&&<p className="success">Message sent. Thanks for reaching out.</p>}<label>Name<input required/></label><label>Email<input required type="email"/></label><label>Message<textarea required rows="6"/></label><button className="button full">Send Message</button></form></main><Footer/></>}
function App(){return <Provider><Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/medicines" element={<Medicines/>}/><Route path="/medicines/add" element={<AddMedicine/>}/><Route path="/scanner" element={<Scanner/>}/><Route path="/reminders" element={<Reminders/>}/><Route path="/history" element={<HistoryPage/>}/><Route path="/caregiver" element={<Caregiver/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Provider>}
createRoot(document.getElementById('root')).render(<BrowserRouter basename={import.meta.env.BASE_URL}><App/></BrowserRouter>);
